### ISSUE TITLE
Call PHP from the front end http://localhost:3000/home/<?= $article->image_url ?>

### ISSUE THREAD

**Issue by kevingzhang** [emmavz/quillmates#10]
I noticed you request this http://localhost:3000/home/<?= $article->image_url ?>
the sournce code is
```
<div class="blog-post-wrap container flex flex-wrap">

				<?php foreach ($articles as $k => $article) : ?>

				<?php
						$bgColor = '#'.getAverageColor($article->image_url);
					?>
```

PHP is no longer supported. 
If you need additional API, please let @emmavz know

**Comment by kevingzhang** [comment]
Please close this issue if you think it is done

**Comment by ehtelahi** [comment]
done
