### ISSUE TITLE
Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by kevingzhang** [emmavz/quillmates#11]
Please use webpack and build the app.
Also write readme.md explain how to run the test.
Currently if you run the test and use locahost:3000 you will see this error.

Note: The original URL localhost:3000/home has changed to localhost:3000. 
@emmavz please also note the URL change.

@ehtelahi Please make sure you add instruction on how to webpack build and run in local

**Comment by ehtelahi** [comment]
There is no need for webpack.

**Comment by ehtelahi** [comment]
This application is working fine.
Let me write a note how you can run the application on your local system.

**Comment by ehtelahi** [comment]
and dont keep the same port in cors which I changed to 88. Application cannot run on 3000 port.

**Comment by ehtelahi** [comment]
I have updated readme.md file in webite directory.

**Comment by kevingzhang** [comment]
I have read it. But this is what we are looking for.
This application will be eventually run in TEAProject. TEA Project doesn't have node.js installed. It will only serve either static resource (HTML, js, CSS), or API call (ajax). So we cannot use node.js here.

The current simulator is not TEA Project runtime, but it is similar. So we need to make it work by running cargo run and launch at HTTP://localhost:3000/

This is something we cannot workaround.  Please figure out how we can make it work

**Comment by kevingzhang** [comment]
Also. FYI. @lxm218

**Comment by kevingzhang** [comment]
One possible solution is to use webpack or whatever tool to compile the whole VUE app into a dist pack. There is one index.html and main.js and a bunch of other resources inside a folder (usually called public , or dist).

**Comment by ehtelahi** [comment]
You should have told me earlier that you have some restrictions. I already spent double amount of time on the project. First in php now changed everything in vue js

**Comment by ehtelahi** [comment]
Vite also generates a dist folder. Let me upload that one. so you can test.

**Comment by kevingzhang** [comment]
Go ahead. make sure you have read backend/service/src/README.md
This is also how you are going to run it. 
Please do NOT use node.js or PHP server which is not what are using.

**Comment by ehtelahi** [comment]
ok. also please upload your images on online and updated path in your main.rs file.

**Comment by ehtelahi** [comment]
public -> dynamic folder contains those images

**Comment by emmavz** [comment]
Are you talking about the mockup images?

**Comment by ehtelahi** [comment]
Only those images that are dynamic.

**Comment by ehtelahi** [comment]
I mean those which are coming from the api. You need to upload them online and update in api

**Comment by kevingzhang** [comment]
that is alright, just let me know the name of those folders, I have known: "public", "src", "dist", anything else? I can update the server backend code to make them work

**Comment by ehtelahi** [comment]
only dist folder contains those images. Let me upload it first.
Also can you please allow 1 more port 88 in cors? So I can do local development.

**Comment by kevingzhang** [comment]
We would better to use telegram or any kind of IM to fast communicate
If you cannot use port 3000, we can change everything to port 88. let me do it now.

**Comment by kevingzhang** [comment]
I used port 8888 now. since 88 is not allowed to use.

**Comment by ehtelahi** [comment]
yes we should use better tool for communication.
you dont need to change all ports to 88. If you do again I will not be able to do local developement even with webpack.
because I cannot run your cargo server and my vue server on the same port technically.
I see you changed your cargo server to 8888. You dont need to change that. Run your cargo server on 3000 but only change port in cors to 8888 or whatever.

**Comment by kevingzhang** [comment]
there should be only one port open. in the real life, it would be 80, but now in our dev machine, we can use whatever port number. But only ONE port open.
Do you want to use 8888 or 3000?
When you get :8888/ you get the index.html, when you post to :8888/api/someapi you get API call.
Please use telegram. @emmavz Are you still working on setting up the telegram channel?

**Comment by kevingzhang** [comment]
Again, you cannot use node.js or any other server running. The only server you can use is the cargo run.

**Comment by kevingzhang** [comment]
If you want to have fast development using vue server, I understood.
let's talk in telegram then. it is faster

**Comment by ehtelahi** [comment]
You are not getting my point. 
I need to run node server + your cargo server on my local system for DEVELOPMENT purpose only. 
So for that we cannot run both servers on single port. Its not possible. It throw an error.
what I am saying is only allow 8888 port in 
.allow_origin(Origin::exact("http://localhost:3000".parse().unwrap())) 
here you need to change port 3000 to 8888 thatsit.

**Comment by ehtelahi** [comment]
If still you are not getting it. Let me change that file myself.

**Comment by ehtelahi** [comment]
send me the telegram link

**Comment by kevingzhang** [comment]
please check yourself.
What I need is when you commit the code, I can test in my cargo run at any port. I am not going to run a development vue server. so it is not a problem I care about. 

Please update your read me, I will follow your instruction to run in my local dev env.
Of course, I will not run node.js. 
I probably need to run npm build first, then load from the local dist folder.

I do not have the telegram channel.   I will need to ask Emma

**Comment by kevingzhang** [comment]
@emmavz Are you there? We need the telegram channel to be setup

**Comment by ehtelahi** [comment]
I am sure there will be way so you can allow multiple ports in cors. Can you please do that? Since I dont know about rust

**Comment by emmavz** [comment]
Telegram link: https://t.me/+s80stsd0RjZiNmEx

**Comment by kevingzhang** [comment]
@ehtelahi please join, then we can continue talking

**Comment by ehtelahi** [comment]
AH I cannot. since telegram is blocked in my country.

**Comment by kevingzhang** [comment]
It is not about CORS, it is complicated. TEA Project is not Web2, it is Web3. There are a lot of restriction.

**Comment by kevingzhang** [comment]
please join telegram. @ehtelahi

**Comment by emmavz** [comment]
@kevingzhang @kevingzhang Since Telegram is blocked, do you use Discord?

**Comment by ehtelahi** [comment]
yes

**Comment by emmavz** [comment]
@ehtelahi @kevingzhang  ^

**Comment by kevingzhang** [comment]
give me the discount server link

**Comment by emmavz** [comment]
https://discord.gg/uATxwMyy

**Comment by ehtelahi** [comment]
done
