### ISSUE TITLE
Some fields are missing. 

### ISSUE THREAD

**Issue by ehtelahi** [emmavz/quillmates#16]
Hi @kevingzhang!
I sent you message on discord 2 days ago. but you didnot see.
There are some data which is missing.
like date_posted on home page
and article description on article page
and liquidation number and user_wallet_balance

**Comment by kevingzhang** [comment]
Please use GitHub issue if any bug related . I will check tomorrow. Thanks

**Comment by kevingzhang** [comment]
I  have added missing data_posted and article_description.
but I will not add user_wallet_balance in the get_article_homepage API.
I will add a new API called get_user_profile. this user profile (including user_wallet_balance)should be there.

**Comment by kevingzhang** [comment]
@ehtelahi when create an issue, always make sure you asisgn to someone who will solve this issue.
If you are not familiar with Github issue, I can give you a list of rules. please let me know.

**Comment by ehtelahi** [comment]
Ok. Next time I will assign.

**Comment by ehtelahi** [comment]
Hi @kevingzhang Please correct spellings of data_posted. Its date_posted. and you should also add dates in database in correct format so I can see on users side. Currently its showing me 0

**Comment by kevingzhang** [comment]
There is not timestamp in gluesql . What you get the time is actually integer. You can use js to convert from integer to human readable time. 

For the wrong data posted. Sorry about that, can you correct in rust source code yourself, or wait for me another hour.

**Comment by kevingzhang** [comment]
I have upated the code. it is now date_posted

**Comment by kevingzhang** [comment]
@ehtelahi 
This is unit test result. You can try on your own using test.http 
```
HTTP/1.1 200 OK
content-type: application/json
content-length: 1338
date: Sat, 30 Apr 2022 18:36:04 GMT

[
  {
    "article_id": 0,
    "article_title": "Why Python is The Future",
    "data_posted": 1651335773,
    "hashtag": "for you, coding",
    "image_url": "http://localhost:8080/dynamic/post-1.png",
    "name": "Ephraim Jones",
    "pfp": "http://localhost:8080/dynamic/profile-1.png",
    "total_invested": 10025
  },
  {
    "article_id": 1,
    "article_title": "Super Chewy Cookies Recipe",
    "data_posted": 1651335773,
    "hashtag": "for you, baking",
    "image_url": "http://localhost:8080/dynamic/post-2.jpg",
    "name": "Eliza Mae",
    "pfp": "http://localhost:8080/dynamic/profile-2.png",
    "total_invested": 7342
  },
  {
    "article_id": 2,
    "article_title": "The Go-To-Market Guide",
    "data_posted": 1651335773,
    "hashtag": "for you, business",
    "image_url": "http://localhost:8080/dynamic/post-3.jpg",
    "name": "Cecelia Hong",
    "pfp": "http://localhost:8080/dynamic/profile-3.png",
    "total_invested": 8961
  },
  {
    "article_id": 3,
    "article_title": "The Rules of Digital Marketing",
    "data_posted": 1651335773,
    "hashtag": "for you, marketing",
    "image_url": "http://localhost:8080/dynamic/post-4.jpg",
    "name": "Melissa Shen",
    "pfp": "http://localhost:8080/dynamic/profile-4.png",
    "total_invested": 9456
  },
  {
    "article_id": 4,
    "article_title": "Building muscle the right way",
    "data_posted": 1651335773,
    "hashtag": "for you, fitness",
    "image_url": "http://localhost:8080/dynamic/post-5.jpg",
    "name": "Darren Jones",
    "pfp": "http://localhost:8080/dynamic/profile-5.png",
    "total_invested": 11275
  }
]
```
If any field incorrect, please point it out. thanks

**Comment by ehtelahi** [comment]
time is in milliseconds?

**Comment by kevingzhang** [comment]
see this https://www.epochconverter.com/

**Comment by kevingzhang** [comment]
In seconds.

**Comment by kevingzhang** [comment]
See this unit test for user_wallet_balance

```
POST http://localhost:3000/api/get_user_profile
content-type: application/json

{
    "user_id": 2
}

###
return
{
    "user_wallet_balance": 111
}

```

**Comment by kevingzhang** [comment]
@emmavz Please note there is one API change about user_wallet_balance and get_article_homepage

**Comment by kevingzhang** [comment]
Note to @ehtelahi Because the initial sql scripts changed due to data_posted mistake. 
Before you run the test, please run the drop table scripts and create new tables, insert data scripts.
They are all inside test.http

otherwise, you will get error due to missing field name date_posted
