### ISSUE TITLE
localhost:8080 shows Error This request couldn't be processed right now. Please try again later!

### ISSUE THREAD

**Issue by kevingzhang** [emmavz/quillmates#19]
Error
This request couldn't be processed right now. Please try again later!

I cannot see any UI now. please fix

**Comment by kevingzhang** [comment]
![image](https://user-images.githubusercontent.com/1761809/166164348-b558c39b-166f-45ea-9c29-f8e24e31d0d6.png)

**Comment by ehtelahi** [comment]
are you sure are you using latest github code?
because I can run it successfully. 
can you check console.log it will show you an error there

**Comment by kevingzhang** [comment]
I Git pull latest code every time I run. 
I checked console log, there is no error. also the network traffic looks good too. you can find them in the screen shot.
To make sure we are on the same page. let me explain how I run it.
I git pull latest code, then go to backend/services folder, run cargo run
go to browser, HTTP://localhost:8080

I hope you run the same way too so that we are on the same page.

Let me know you still not seeing any problem after doing this. thanks

**Comment by ehtelahi** [comment]
you need to run this command also:
npm run build
and yes I am seeing no error.

**Comment by kevingzhang** [comment]
Aha, you are right, I did not npm run build. so I am running the older code. sorry, my bad.
I found an error get_user_profile. I will take a look at it now

**Comment by kevingzhang** [comment]
I've fixed the multi-threading issue caused get_user_profile stop working.
