### ISSUE TITLE
Please allow cors policy

### ISSUE THREAD

**Issue by ehtelahi** [emmavz/quillmates#7]
I am trying to get api results with ajax but its throwing me an error of cors. 
Please allow it.

**Comment by kevingzhang** [comment]
I see. that is right, I have not enable it.
I will enable it today.

**Comment by kevingzhang** [comment]
But if I server the HTML from my backend server, do I still enable CORS? I think I do not have to , right?

**Comment by kevingzhang** [comment]
@ehtelahi

**Comment by ehtelahi** [comment]
yes If you serve html from the backend then its not required.

**Comment by ehtelahi** [comment]
I converted .html file to .php file and everything is working fine but emmavz told me why you are running another server (php server). so now I thought I should convert back to .html and use ajax

**Comment by kevingzhang** [comment]
Yes,  please convert it back to html. I will server the static resources from the backend server.
In our final version, it will be served from the TeaProject platform. So PHP is not supported.

**Comment by ehtelahi** [comment]
ok... so It means you will integrate api yourself?

**Comment by kevingzhang** [comment]
yes, I made those API

**Comment by ehtelahi** [comment]
ok.. but still there are some features that required ajax requests. Like voting feature etc. so you need to enable cors somehow.

**Comment by kevingzhang** [comment]
why do you need cors? If you load the html/js/css from the same ajax server? 
If you run it from localhost:3000, all ajax API call will go to the same localhost:3000, there is no cors.

**Comment by kevingzhang** [comment]
I have support cors. still at port 3000, but I also add support for local static file (such as index.html) at port 8080.

you can see the changes in test.http
```
GET http://localhost:8080/index.html
### 
POST http://localhost:3000/api/get_article_list_and_view
content-type: application/json

{
    "user_id": 1,
    "start_index": "1",
    "number_of_article": "5"
}
####
```

You can see how to use them.

Note the index.html is in your current ./frontend/website folder. I renamed the index.php to index.html for testing.

**Comment by ehtelahi** [comment]
Hi kevingzhang!
I am still not able to send ajax request

**Comment by ehtelahi** [comment]
Its throwing me an erro for cors

**Comment by kevingzhang** [comment]
please write readme  let me run your code so that i can reproduce your bug

**Comment by ehtelahi** [comment]
I just updated index.html file with ajax code. You can simply open .html page and you will see the error in browser console

**Comment by kevingzhang** [comment]
![image](https://user-images.githubusercontent.com/1761809/164150072-8e11f86f-a710-4d04-b734-e9264fef116a.png)
Can you see this error? You are request a strange URL http://localhost:8080/<?= $article->author_pfp ?>
Of course, there is no such a file called that name.
I do not know why you are request such a URL?

**Comment by kevingzhang** [comment]
another issue, see the screenshot
![image](https://user-images.githubusercontent.com/1761809/164150824-198a2556-c8b7-41a6-abf5-7bb74c6c80b1.png)

The content type need to be the same as the unit test. let me show below:
![image](https://user-images.githubusercontent.com/1761809/164150874-bf2c13f4-5eaf-4095-aa2e-3ac429fe20e4.png)

**Comment by kevingzhang** [comment]
One breaking change: Please use localhost:3000/home to load index.html

**Comment by kevingzhang** [comment]
After you repalce the 8080 with the single 3000 port. There should not be any CORS issue. This is only one domain.

**Comment by kevingzhang** [comment]
I have helped you fixed the problem. See my latest commit https://github.com/emmavz/cypher/commit/6e2b4a1f8ef9dc8be308719a9262a9134dac54c6

but you still need to remove the PHP

**Comment by ehtelahi** [comment]
Thanks. Cors has gone.
